version: '3'
services:

  dash:
    build:
      context: ./
      dockerfile: dockerfile-dash
    container_name: web_job_analysis
    restart: always
    ports:
      - "8000:8050"
    environment:
      - TARGET=LIVE
    volumes:
      - ./app:/app
